export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_RENTALS = "GET_RENTALS";
export const GET_RENTAL = "GET_RENTAL";
export const GET_RENTALSTATS = "GET_RENTALSTATS";
export const DELETE_RENTAL = "DELETE_RENTAL";
